### ISSUE TITLE
mps-youtub​e with portable Python or standalone on Windows

### ISSUE THREAD

**Issue by ZaxonXP** [np1/mps-youtube#121]
Dear Nagev,

I found the mps-youtube tool very useful and I would like to use it in a portable mode.

Currently it requires the Python installation which is not so convenient. I tried to use it with the Portable Python but so far I failed to install the mps-youtube with it. The best would be to create the Windows exe file and put it on GitHub, but I am not so advanced in Python yet to achieve this.

Could you please add some instructions on the GitHub page how to install it on the Portable Python or better provide precompiled version for Windows?

Best regards,
ZaxonXP

**Comment by ids1024** [comment]
A standalone binary can now be built with `python setup.py py2exe`, assuming py2exe is installed. A prebuild binary will be available with the next release.

**Comment by ids1024** [comment]
Available with latest release. See the download attached to the release:

https://github.com/np1/mps-youtube/releases/tag/v0.2.5

**Comment by ids1024** [comment]
@ZaxonXP Have you tried the standalone binary provided with the latest release? I don't ordinarily run Windows and would like to know if it is working properly.
