### ISSUE TITLE
Stopping mpsyt leave mplayer in an undefined state

### ISSUE THREAD

**Issue by SebCorbin** [np1/mps-youtube#130]
Hello,
(First, great work with this software :+1: )

When hitting `Ctrl+C` during the execution of `mpsyt playurl https://www.youtube.com/watch?v=kvDMlk3kSYg`, `mpsyt`is killed but mplayer is not.

**Comment by np1** [comment]
This issue no longer seems to be occurring on develop branch, although I'm not sure which commit has fixed it!

**Comment by ids1024** [comment]
@np1 With 0.2.2 released you can close this as well as #202.
