### ISSUE TITLE
Add MultiConnection Download

### ISSUE THREAD

**Issue by xubuntu4iran** [np1/mps-youtube#132]

**Comment by ids1024** [comment]
What about a `download_command` option, so that a user could make mpsyt download a video using programs like aria2c?

**Comment by ids1024** [comment]
@np1 You can probably mark this as "implemented" now.

**Comment by np1** [comment]
Version 0.2.2 released with `download_command` config option

type `help dl-command` for help.

To enable 4 connections for downloads using aria2c:
```
set download_command aria2c -k 1M -s4 -x4 --dir=%d --out=%f %u
```
