### ISSUE TITLE
Playlist improvements

### ISSUE THREAD

**Issue by hotice** [np1/mps-youtube#14]
In a playlist you can skip to the next track but you can't go to the previous track or play a certain track.

It would also be useful to use vim keys for navigations (this was also used in Google Reader and is now used in Google+ or Facebook for instance - e.g.: J to go to the next track or K to go to the previous track).

**Comment by np1** [comment]
previous / next track is implemented with `<` and `>` keys in version 0.2.2

you can use `j` and `k` for next/prev by creating a file called mplayer-input.conf and/or mpv-input.conf with the following lines:

- mpv-input.conf:
```
j playlist_next
k playlist_prev
```
- mplayer-input.conf:
```
j pt_step 1
k pt_step -1
```
The file(s) must reside in the mps-youtube config dir (usually `~/.config/mps-youtube/` on Linux).
