### ISSUE TITLE
Missing video in search ressult, probably some title parse problem

### ISSUE THREAD

**Issue by occulkot** [np1/mps-youtube#177]
I tried to find one video using mpsyt and found issue proabble caused by its title.
Search string was: "mgla clandestine"
all results appears same as on youtube expect video https://www.youtube.com/watch?v=RAGKV3oyqo0 - "Mgła &Clandestine Blaze live".

I think that problem is caused by "&C" in the video name, but i cannot see any debug options in the settings to provide more details

**Comment by np1** [comment]
It's working ok for me:

![screenshot - 080115 - 22 09 00](https://cloud.githubusercontent.com/assets/2274410/5661732/32a5e50a-9783-11e4-93b6-f277ea0a7ca2.png)

I would suggest you check that the [search_music setting is set to False](https://github.com/np1/mps-youtube/wiki/Troubleshooting#search-results-not-relevant-or-differ-from-youtube-website)

**Comment by occulkot** [comment]
Thx! I didnt consider changing this option.

**Comment by np1** [comment]
Good!
