### ISSUE TITLE
Don't use `q` for the next track.

### ISSUE THREAD

**Issue by lightonflux** [np1/mps-youtube#18]
The are few but important keys that always™ have the same function. Like q and ctrl+c for quit and SIGINT (well kind of) especially in a terminal.

At the moment q has several different meanings in your application (from end user perspective): one is "return" (only one track playing) the other is "next track" when you play more tracks. I think i understand why you did it as a programmer. :) Would you be "confused" if you use VLC and it would use `q´ the same way?

Instead i suggest using `<` and `>` for next and previous track. Or `n` and `p` or both.

But i don't know how that would work with videos when mplayer or mpv have focus and grab the keys strokes.

**Comment by chmol** [comment]
Hello, with mps-youtube-git 0.2.1 from AUR neither 'n' nor 'p' work as indicated in the interface 
`[n] next/prev [p] `  but '< > ' does

**Comment by ids1024** [comment]
@chmol It has been changed to match mpv/mplayer defaults.

**Comment by chmol** [comment]
@ids1024 shouldn't the interface be updated too ? 
![screenshot from 2015-01-31 17 40 37](https://cloud.githubusercontent.com/assets/8171862/5988814/4cf37b08-a970-11e4-83e5-a1ec519567b4.png)

**Comment by ids1024** [comment]
I hadn't noticed that, and have now submitted a pull request to fix it.

**Comment by chmol** [comment]
:+1:

**Comment by np1** [comment]
< and > are used for prev/next track in v0.2.2
