### ISSUE TITLE
Playing a media play every version of it

### ISSUE THREAD

**Issue by chmol** [np1/mps-youtube#182]
Since several version ( currently 0.2.1-2 with mvp ) when i chose one song or a playlist it play every version of it : m4a, mp4, flv, after starting the next one. I don't kow if it is intended but it made the tool unusable for casual listening.

Thanks

**Comment by np1** [comment]
Hi, what is the output of `mpsyt --version` ?

**Comment by chmol** [comment]
here you are  : 

mpsyt version  : 0.2.1 
pafy version   : 0.3.66
Python version : 3.4.2 (default, Oct  8 2014, 13:44:52) 
[GCC 4.9.1 20140903 (prerelease)]
Processor      : 
Machine type   : x86_64
Architecture   : 64bit, ELF
Platform       : Linux-3.16.7.3-1-MANJARO-x86_64-with-glibc2.3.4
sys.stdout.enc : UTF-8
default enc    : utf-8
env:TERM       : xterm
env:SHELL      : /bin/bash
env:LANG       : en_GB.UTF-8

**Comment by np1** [comment]
Thanks, I don't know why this might be happening. Could you try running `mpsyt --logging` and then perform a search and play an item.

After the problem occurs (i.e., after more than one version of the item gets played), quit mpsyt and then paste the contents of `/tmp/mpsyt.log`, either here or at a pastebin site.

Thanks!

**Comment by chmol** [comment]
Here you are http://pastebin.com/uYdRq4hk

i tried with a first media then remembered i had to make a list to have the problem and played 2 files. The i switched to the next one with "q" ( but some behaviour without) .

**Comment by np1** [comment]
Thanks for that. It seems mpsyt believes the stream failed to play so is trying the next available stream. Could you let me know whether this also happens when using mplayer?
(to try, install mplayer and enter `set player mplayer` in mpsyt)

**Comment by ids1024** [comment]
This must be issue #155.  Using mps-youtube-git should work as an alternative to switching to mplayer.

**Comment by np1** [comment]
Right @ids1024, I missed that. 
@chmol, can you confirm whether using mplayer or [mps-youtube-git from the AUR](https://aur.archlinux.org/packages/mps-youtube-git/) has helped?

**Comment by nivit** [comment]
I have the same issue with mps-youtube-0.2.1, but it happens only with mpv as player. When a song finishes, the message `error: retrying` appears for a moment. 
All works fine with mplayer at least on my system:

    mpsyt version  : 0.2.1 
    pafy version   : 0.3.68
    Python version : 2.7.9 (default, Dec 25 2014, 01:19:43) 
    [GCC 4.2.1 Compatible FreeBSD Clang 3.3 (tags/RELEASE_33/final 183502)]
    Processor      : amd64
    Machine type   : amd64
    Architecture   : 64bit, ELF
    Platform       : FreeBSD-10.1-STABLE-amd64-64bit-ELF
    sys.stdout.enc : UTF-8
    default enc    : ascii
    env:TERM       : xterm-256color
    env:SHELL      : /usr/local/bin/zsh
    env:LANG       : it_IT.UTF-8

**Comment by chmol** [comment]
I don't have access to my computer at the moment sorry, I hope I can give a feedback soon 

Le 28 janvier 2015 05:57:53 UTC, nagev <notifications@github.com> a écrit :
>Right @ids1024, I missed that. 
>@chmol, can you confirm whether using mplayer or [mps-youtube-git from
>the AUR](https://aur.archlinux.org/packages/mps-youtube-git/) has
>helped?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/np1/mps-youtube/issues/182#issuecomment-71785321

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by ids1024** [comment]
@nivit The last release of mpsyt does not work with mpv 0.7+ on Unix systems (issue #155).  This is fixed in the develop branch.

**Comment by nivit** [comment]
Thanks!

**Comment by chmol** [comment]
So, the git version from AUR fixed the problem but lead to an other one : "n" does not play to the next song as indicated on the interface but > does.

Finding this tread I'll add a comment
https://github.com/np1/mps-youtube/issues/18

Thanks :)

**Comment by np1** [comment]
Resolved in v0.2.2
