### ISSUE TITLE
Installed with Hombrew - won't launch

### ISSUE THREAD

**Issue by lacostenycoder** [np1/mps-youtube#186]
Can't start the program from command line.  Looks like it's installed.  I installed with brew install mplayer.
What am I missing?

**Comment by lacostenycoder** [comment]
OK I was able to install from source but maybe update the installation instructions because brew install mplayer doesn't install mps-youtube.

**Comment by np1** [comment]
Thanks, I amended the install notes to state that the Mac and Windows instructions are additional https://github.com/np1/mps-youtube/commit/e2feb713cef3b5acf55dda97e87a39ec3ff18c5c
