### ISSUE TITLE
Age-restricted videos

### ISSUE THREAD

**Issue by spvkgn** [np1/mps-youtube#197]
Hi, some videos on youtube have age-restriction - says "Sign in to confirm your age".
Would be great if you can add this feature in the future releases.

**Comment by np1** [comment]
Thanks for reporting this. It's an issue with pafy. I noticed it earlier as some [tests were failing](https://travis-ci.org/np1/pafy/jobs/47869048).

I should be able to sort it by implementing something similar to this [youtube-dl commit](https://github.com/rg3/youtube-dl/commit/beb95e778170895c1435f55b71e3d76cbd9d8bcf#diff-bd8242a0122c5207531954b67e6e51f0R969)

**Comment by np1** [comment]
This issue has been resolved in pafy. Upgrading pafy to v0.3.72 should prevent it from asking you to sign in.
