### ISSUE TITLE
Playback fails altogether after computer sleep

### ISSUE THREAD

**Issue by strawhead** [np1/mps-youtube#211]
**Computer went to sleep** with playing audio, when it woke up, audio resumed -- presumably until the buffer emptied, and then **stopped working**. That's not a major problem, but `mpsyt` now doesn't work at all. It can search videos and playlists as usual, but will not play anything.

**Tried** rebooting, and eventually clearing `rm -r ~/.config/mps-youtube/*` and then re-installing `mplayer` and `mps-youtube`. No joy. It just says, "Sorry, this track is not available," for all tracks. This is the same error received before updating.

The now-updated version info:

    mpsyt version  : 0.2.1 
    pafy version   : 0.3.66
    Python version : 2.7.9 (default, Dec 19 2014, 06:00:59) 
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
    Processor      : i386
    Machine type   : x86_64
    Architecture   : 64bit, 
    Platform       : Darwin-14.1.0-x86_64-i386-64bit
    sys.stdout.enc : None
    default enc    : ascii
    env:TERM       : xterm-256color
    env:SHELL      : /bin/bash
    env:LANG       : en_US.UTF-8

**Comment by np1** [comment]
Hi, I'm not sure why this is happening.

Could you try to run this in the terminal, it should output some data about a YouTube video.
```
python -c "import pafy; print pafy.new('j8Tcjff_yXQ')"
```

If that works please try:
```
pafydebug=1 python -c "import pafy; print pafy.new('j8Tcjff_yXQ').streams[0].url"
```
Which should output some debug messages and then a url. Please let me know how it goes.

**Comment by strawhead** [comment]
It resumed working normally again. Sorry for the delay.
