### ISSUE TITLE
-v flag when show_video is set to False

### ISSUE THREAD

**Issue by bendem** [np1/mps-youtube#213]
When having `show_video` set to `True`, we can use the `-a` flag to play the audio file only, but when `show_video` is set to `False`, there is only `-f` to play the video (but only in fullscreen mode).
It would be nice to have a `-v` flag to show the video.

**Comment by np1** [comment]
There is -w for windowed mode which will do that.

**Comment by bendem** [comment]
Oh nice, I missed that!
