### ISSUE TITLE
Progress bar creates new lines each second

### ISSUE THREAD

**Issue by hotice** [np1/mps-youtube#215]
With the latest mps-youtube 0.2.3, the progress bar creates new lines each second which I guess isn't supposed to happen. Screenshot: http://i.imgur.com/jNeCYC3.png This happens with GNOME Terminal 3.6.2 available in Ubuntu 14.10 (I also tested it with Guake terminal and it doesn't happen).

This occurs with both mpv and mplayer2 (tested under Ubuntu 14.10).

**Comment by np1** [comment]
Thanks for reporting this.
I've seen it happen before when the window width is too small.
I am able to reproduce the issue by setting the width to 75 or less
What is the output of `tput cols` ?

**Comment by hotice** [comment]
``
$ tput cols
72
```

Indeed, if I increase the window width, this no longer occurs.

**Comment by np1** [comment]
I don't think this is a new issue. I just reproduced it using v0.2.1 and v0.01.46 by setting the window width to 75 columns. I think the default terminal width on most systems is 80 so it's not a huge deal although I will try to get it to play nicely with smaller widths.

**Comment by hotice** [comment]
Could be, I just didn't notice it until now...

**Comment by np1** [comment]
The help screens and

**Comment by np1** [comment]
fixed!

**Comment by littmus** [comment]
Is there no one suffering this issue on windows cmd?
I fixed myself by adding one line.
```
def writeline(text):
    """ Print text on same line. """
    width = getxy().width
    if mswin: width -= 1
```

**Comment by ids1024** [comment]
@littmus I've done something similar in commit 67f232645f95fd45e8e728fc1d65b090f7c1b4e0. I am not sure why this is needed.
