### ISSUE TITLE
Album search not working all the time.

### ISSUE THREAD

**Issue by EduardoRT** [np1/mps-youtube#217]
Hi! I don't really know why but the album search isn't quite working, for example searching for 'album Californication' doesn't return anything on the first try but if you keep trying it will match it eventually, also it has the same problem with playing the album once it's been found or while searching for the correct artist.

I've asked some friends and they're having this issue too.

Nice software btw, I use it daily :)

**Comment by RobertoGongora** [comment]
:+1:

**Comment by np1** [comment]
I have noticed this too, it will need to be looked at.

**Comment by ids1024** [comment]
It looks like musicbrainz is returning a 503 error.  The code could retry when it gets that.

**Comment by ids1024** [comment]
Here is an explanation for why this is happening:
http://musicbrainz.org/doc/XML_Web_Service/Rate_Limiting

**Comment by np1** [comment]
Thanks @ids1024, after reading through that I changed the user-agent as they advise and have had much more success with the `album` command.

**Comment by ainola** [comment]
If it's not completely solveable due to the rate-limiting it may be worthwhile to have a meaningful message on a 503 return.

**Comment by knutshub** [comment]
Why does this happen? 

I build myself a test script only using the functions '_get_mb_album' and '_get_mb_tracks' and everytime I get correct results for the search (except for the UnicodeEncodeError issues I just opened). It doesn't matter how often I run the script.

Can it be that the error is somewhere else?
