### ISSUE TITLE
Longer online playlist pages

### ISSUE THREAD

**Issue by Atema** [np1/mps-youtube#218]
I would love to be able to view all items in an online playlist (when using pl <URL>) at once, especially for playing and shuffling the whole playlist at once, instead of playing per block of 20.

**Comment by np1** [comment]
After you open the playlist, enter `dump`
This will retrieve up to 200 items of the playlist so you can play / shuffle them.

There is an issue open about the fact that it is [limited to 200 items](https://github.com/np1/mps-youtube/issues/192)

**Comment by Atema** [comment]
Hadn't noticed that. Thanks!
