### ISSUE TITLE
bug to run mps-youtube in windows 7

### ISSUE THREAD

**Issue by call5** [np1/mps-youtube#223]
Hello, I tried to install  mps-YouTube on Windows 7, I have python 3.4 installed, thanks to miniconda and mpv installed already, I thus followed the procedure of installation described in the readme by using pip but by starting mpsyt I have a problem which you can observe in this link bellow. Thank you for helping me to solve it. sorry for bad english
http://i.imgur.com/0XBBzyV.png
http://i.imgur.com/BZ2GbS8.png
http://i.imgur.com/HH4ZNVM.png
http://i.imgur.com/HZ0AfOn.png
http://i.imgur.com/RsXBpJR.png
http://i.imgur.com/4PhngLe.png
http://i.imgur.com/v7uJjlx.png
http://i.imgur.com/gyysXhZ.png
http://i.imgur.com/sX6HN9Y.png
http://i.imgur.com/Rm4P6dc.png
http://i.imgur.com/6fPofLY.png

**Comment by ids1024** [comment]
I had a similar issue when I tested under Windows 7.  Try running `set player mpv.com`.

**Comment by call5** [comment]
i try running this : 
- `mpsyt set player mpv.com` return http://i.imgur.com/eUnOjxp.png and http://i.imgur.com/nZ92mUV.png
- `mpsyt set player mpv.exe` return http://i.imgur.com/AGGC73s.png , http://i.imgur.com/AAMobfK.png and http://i.imgur.com/mPCgLGt.png
- `mpsyt set player mplayer[.exe]` return http://i.imgur.com/2Eafd8Q.pngand http://i.imgur.com/NkeXHaE.png

**Comment by ids1024** [comment]
It probably shouldn't be testing the mpv version on initialization.  Install my branch with a fix for that using the command `pip install -U git+https://github.com/ids1024/mps-youtube` and try running `set player mpv.com` again.

**Comment by call5** [comment]
it's not work for me: https://i.imgur.com/Jij4JFo.png

**Comment by ids1024** [comment]
Then try this command instead: `pip install -U https://github.com/ids1024/mps-youtube/zipball/develop`

**Comment by call5** [comment]
now it's good but my first problem not fix https://i.imgur.com/exGSRbT.jpg

**Comment by call5** [comment]
i think config file in %appdata%\Roaming\mps-youtube locate here https://i.imgur.com/sX6HN9Y.png not good, maybe if possible to let me see you config file

**Comment by ids1024** [comment]
I pushed another commit that may fix it.  Reinstall with the same command and try again.

**Comment by ids1024** [comment]
> i think config file in %appdata%\Roaming\mps-youtube locate here https://i.imgur.com/sX6HN9Y.png not good, maybe if possible to let me see you config file

That's a binary file, not plain text, so it actually should look like that.

**Comment by call5** [comment]
wow thank you, now it's work http://i.imgur.com/kbYP1IB.jpg 
just if i not want see the progress bar, how i disabled this ?

**Comment by ids1024** [comment]
`set show_status False` should hide the progress bar.  It shouldn't look like that; it's supposed to be on one line.

**Comment by call5** [comment]
Yes, normally he have to be on a line finally that would have been good but as he posts a line every second, I prefer to deactivate him until possible correction.
Thank you anyway to have brought me your help, I hope that that can be corrected to display on a line soon

**Comment by ids1024** [comment]
Ok, the second issue should be fixed in git now.

Install with `pip install --upgrade https://github.com/np1/mps-youtube/archive/develop.zip` if you want to test it.
