### ISSUE TITLE
Sort users uploads

### ISSUE THREAD

**Issue by r8b7xy** [np1/mps-youtube#228]
While searching all uploaded songs of user it'd be welcome to sort songs in few possible orders.
e.g. date added (oldest-newest and opposite), most popular.
How sorting is handled right now (date added/alphabetical?)?

**Comment by np1** [comment]
The order is controlled by the value given to the `set order` command.

e.g., `set order views`

type `help set` for more info

**Comment by r8b7xy** [comment]
Thank you.
