### ISSUE TITLE
can't list yt uploads by username with 'user <username>' cmd when username includes white-spaces

### ISSUE THREAD

**Issue by r8b7xy** [np1/mps-youtube#232]
I can't list yt uploads by username with 'user <username>' cmd when username includes white-spaces.
for e.g. [the29nov films [encore]](https://www.youtube.com/channel/UCBJFVeFCJmjT_jclj5oc93A)
I still can find this user with 'user BJFVeFCJmjT_jclj5oc93A' cmd but some of the tracks are not listed in the output.

**Comment by r8b7xy** [comment]
Next example - [hyperspace III](https://www.youtube.com/channel/UCQJrF_javx1TMQpBl19nATg) is seen in mps-yt as 'QJrF_javx1TMQpBl19nATg'.

**Comment by ids1024** [comment]
It looks like this is working now, probably due to #256.
