### ISSUE TITLE
Support for youtube "Mix" playlists

### ISSUE THREAD

**Issue by m8r-yj1ftv** [np1/mps-youtube#241]
I'm talking about the ones that pop up as first in related videos, for example:
https://www.youtube.com/watch?v=JmcA9LIIXWw&index=7&list=RDeFTLKWw542g
Searching for playlists doesn't bring them up in results.

It would be great if they could be either pulled up from related, found in playlists or found anywhere else. ;)
Anyway, I appreciate your great work.

**Comment by lol768** [comment]
https://www.googleapis.com/youtube/v3/playlistItems?part=contentDetails%2Csnippet&playlistId=RDeFTLKWw542g seems to work, so the playlists can at least be shown using the existing code.

I did some experimentation and it's definitely possible to grab the playlist id from the related videos sidebar, it just can't be done with the API:

```python
#!/usr/bin/env python3
import requests
import bs4
from urllib.parse import urlparse, parse_qs

class YouTubeMix():
    SELECTOR = "a.mix-playlist" # public static final String

    # public String
    def grab_mix_playlist_id(self, video_id):
        response = requests.get("https://www.youtube.com/watch", params={"v": video_id})
        bs = bs4.BeautifulSoup(response.content)
        items = bs.select(self.SELECTOR)
        if len(items) != 1:
            return None
        else:
            url = parse_qs(urlparse(items[0]['href']).query)
            return url['list'][0]


if __name__ == "__main__":
    mix = YouTubeMix()
    print(mix.grab_mix_playlist_id("eFTLKWw542g")) # returns RDeFTLKWw542g
```

Not sure how @ids1024 would feel about BeautifulSoup being another (optional?) dependency since it doesn't seem possible to get any information about the automatically generated mix playlists via the official API.

**Comment by ids1024** [comment]
@lol768 I think it's alright to implement this by scraping the html, as long as there is no other way. BeautifulSoup may not be absolutely necessary; there is also the lower level `html.parse` module included with python.

**Comment by lol768** [comment]
@np1 

My initial thought was that we might be able to do this without scraping the HTML - The Android YouTube app shows the mix in the suggestions pane below the video and I'd be willing to bet the Android app isn't scraping HTML to get that information.

Unfortunately, the android app is [heavily obfuscated](http://i.imgur.com/E5FggZl.png) and makes calls to URLs such as "https://www.google.com/youtube/accounts/registerDevice?type=GDATA&developer=%s&serialNumber=%s" which makes me think it's unlikely we'd be able to use the same API as the app for this.

-----

Here's my implementation using html.parser:

```python
#!/usr/bin/env python3
import requests
import bs4
from html.parser import HTMLParser
from urllib.parse import urlparse, parse_qs

class MixParser(HTMLParser):
    final_link = None
    def handle_starttag(self, tag, attrs):
        if tag == "a" and self.final_link is None:
            dkeys = dict((x, y) for x, y in attrs)
            if "class" in dkeys and "mix-playlist" in dkeys['class'] and "href" in dkeys:
                self.final_link = dkeys['href']

class YouTubeMix():

    # public String
    def grab_mix_playlist_id(self, video_id):
        response = requests.get("https://www.youtube.com/watch", params={"v": video_id})
        parser = MixParser()
        parser.feed(str(response.content))
        if parser.final_link is None:
            return None
        else:
            url = parse_qs(urlparse(parser.final_link).query)
            return url['list'][0]


if __name__ == "__main__":
    mix = YouTubeMix()
    print(mix.grab_mix_playlist_id("eFTLKWw542g"))
```
It's not quite as flexible as the BeautifulSoup implementation, but it does seem to work.

If that looks okay to you, I'll look at making a PR to add some sort of mix command.

**Comment by ids1024** [comment]
Looks alright. It would be better if it used the api somehow, but if that isn't possible, this implementation should be fine.

**Comment by lol768** [comment]
np1/pafy#88

**Comment by lol768** [comment]
@m8r-yj1ftv I've added a mix command which you can use on a video item. Does this work for you?

**Comment by m8r-yj1ftv** [comment]
Yes! That's exactly what I had in mind. Thank you so much!

**Comment by dantefff** [comment]
This feature stopped working for me in some songs. It says 
>  Youtube Error 404: The playlist identified with the request's <code>playlistId</code> parameter cannot be found.                                                                         

I would like to take a look to the code but I can't see the commit where it was implemented. @lol768 can you point me to your commit/pull request?
