### ISSUE TITLE
Add youtube playlists suppost

### ISSUE THREAD

**Issue by NedkoHristov** [np1/mps-youtube#245]
Improvement proposition:

It will be great if user can play youtube playlists too plus make them as local playlists as well.

**Comment by bendem** [comment]
[It's already possible](https://github.com/np1/mps-youtube/blob/develop/README.rst#features).

You can type `help playlist` to get informations about local playlists and `help play` to get informations about how to read youtube's playlists.

**Comment by NedkoHristov** [comment]
I'm terribly sorry for opening the thread again, but I have troubles using the playlists.
The mps says that I need to provide 11 digit playlist ID, but the ID generated is more than that.
I test with this one https://www.youtube.com/playlist?list=PL67ijmd_eBYPz9jTZFrSQQOfyacBYEBxp - PL67ijmd_eBYPz9jTZFrSQQOfyacBYEBxp

Thanks in advice,
Nedko

**Comment by bendem** [comment]
I typed `pl PL67ijmd_eBYPz9jTZFrSQQOfyacBYEBxp` in the mpsyt console and got the playlist:
![](http://i.imgur.com/kPu81Lc.png)

If you can't do that, there might be a problem with mps, in which case, I'm not the best person to answer.

**Comment by mechakin** [comment]
Neither `help play` nor `help playlist` actually mention the `pl` command, as far as I can tell. The closest I found was `play`, which, while it mentions playlist IDs, doesn't accept the URLs of Youtube playlists, only local ones (presumably, I couldn't test it as I have no playlists due to the recent search API issues, and the help article it's in has the heading 'using local playlists'). `pl` *does* exist and work, though. Is it actually documented anywhere?

**Comment by lol768** [comment]
> \> **help search**
> Searching and Retrieving
  
> set search_music false - search all YouTube categories.
  set search_music true  - search only YouTube music category.
  
>/<query> or .<query> to search for videos. e.g., /daft punk
  //<query> or ..<query> - search for YouTube playlists. e.g., //80's music
  n and p - continue search to next/previous pages.
  
>album <album title> - Search for matching tracks using album title
  user <username> - list YouTube uploads by <username>.
  user <username>/<query> - as above, but matches <query>.
  userpl <username> - list YouTube playlists created by <username>.
 **pl <url or id> - Open YouTube playlist by url or id.**
  url <url or id> - Retrieve specific YouTube video by url or id.
  
>r <number> - show videos related to video <number>.
  u <number> - show videos uploaded by uploader of video <number>.
  c <number> - view comments for video <number>

**Comment by NedkoHristov** [comment]
As I got the same answer as @mechakin I believe you can update a bit the help info to include the youtube playlists help on an easier place.
