### ISSUE TITLE
Search results are totally different from those on the official youtube site.

### ISSUE THREAD

**Issue by hashken** [np1/mps-youtube#246]
I searched for `romanov history of russian dynasty` and these are the top 5 results in mpsyt.

    THE LAST ROMANOVS
    Teh Romanov Rap
    The AP European History Song
    In the Basement, the Story of the Romanovs
    A look inside the Russian Imperial Yacht "Standart"

Whereas the search in youtube (in a private browser window to ensure the results are not affected by user preferences) produces the following results.

    The Romanovs. The History of the Russian Dynasty - Episode 1. Documentary Film. Babich-Design. 2013
    The Romanovs. The History of the Russian Dynasty - Episode 2. Documentary Film. Babich-Design. 2013
    The Romanovs. The History of the Russian Dynasty - Episode 3. Documentary Film. Babich-Design. 2013
    The Romanovs. The History of the Russian Dynasty - Episode 8. Documentary Film. Babich-Design. 2013
    The Romanovs. The History of the Russian Dynasty - Episode 6. Documentary Film. Babich-Design. 2013

The results returned by youtube were what I was actually searching for. Why are the results from mpsyt varying from that of youtube search?

**Comment by np1** [comment]
Try `set search_music false` and `set order relevance` then repeat the search

**Comment by hashken** [comment]
That solved the problem. Thanks
