### ISSUE TITLE
https://youtube.com/devicesupport on search results

### ISSUE THREAD

**Issue by spvkgn** [np1/mps-youtube#249]
I have noticed it today. On first num 'https://youtube.com/devicesupport' from 'youtubehelp' user appears with every search or user list.

**Comment by knutshub** [comment]
I'm not completely sure. But I think this is the link to the API version 3 page including the relevant information for searching:
https://developers.google.com/youtube/v3/docs/search

**Comment by spvkgn** [comment]
I don't fully understand why this link appears. Would be nice find a way to remove it from search results.

**Comment by GijsTimmers** [comment]
Related: https://github.com/rg3/youtube-dl/issues/5483

**Comment by JamesTheAwesomeDude** [comment]
@GijsTimmers I don't think it's just related; I think it's a full duplicate.

The other issue is also about the exact same thing: ytsearch only showing that error page.

**Comment by ids1024** [comment]
See np1/pafy#78

Mpsyt may soon stop working without a fix. That video is not the main issue.

**Comment by RPiAwesomeness** [comment]
Yeah, @ids1024 is right. If you go to http://www.youtube.com/devicesupport there's a page about the Youtube API being upgraded and "Certain older Youtube apps" not working after late May.

@np1 Gotta fix this D:

**Comment by JamesTheAwesomeDude** [comment]
rg3/youtube-dl#5483 was resolved with rg3/youtube-dl@b4c0806

Does that resolve this as well?

**Comment by lol768** [comment]
The rg3/youtube-dl solution seems preferable to me than using the newer API.

**Comment by JamesTheAwesomeDude** [comment]
It's a little funny to think that, as @lol768 pointed out, a third-party borderline TOS-violating ripper written in Python is actually going to end up being a more reliable and useful API than anything provided by Google themselves..

I guess that's just the world we live in these days. :expressionless:

**Comment by jrenner** [comment]
I saw this as top search result for a couple weeks. Now it is the only result I see returned from any search,.

**Comment by lol768** [comment]
@jrenner Yeah, this is how they approached/are approaching phasing out the API. They first added the result, and are now replacing it entirely.

> In early May, Data API v2 video calls will start returning only the warning video introduced on April 20. Users will not be able to view other videos on apps that use the v2 API video calls. See youtube.com/devicesupport for affected devices.

> By late May, v2 API calls except for comments and captions will receive 410 Gone HTTP responses. You can test your application’s reaction to this response by pointing the application at eol.gdata.youtube.com instead of gdata.youtube.com. While you should migrate your app as soon as possible, these features will work in the Data API v2 until the end of July 2015 to avoid any outages.

**Comment by meesameesa** [comment]
@np1 any plans on moving to the new version of the API?
