### ISSUE TITLE
failed to create process.

### ISSUE THREAD

**Issue by call5** [np1/mps-youtube#250]
hello i try to install and upgrade mps-youtube develop in windows 8, if i run `pip install mps-youtube`,`mpsyt`  work nice but if i try to launch this for upgrade to develop branch `pip install -U git+https://github.com/np1/mps-youtube` or `pip install -U https://github.com/np1/mps-youtube/zipball/develop` if i run `mpsyt` i have this "failed to create process." .

**Comment by ids1024** [comment]
Solved: #274
