### ISSUE TITLE
NON ISSUE:   question RE: API v3

### ISSUE THREAD

**Issue by cirrusUK** [np1/mps-youtube#257]
Are the fine devs of mps-youtube planning on migrating to V3 of the API as mentioned here ?
http://youtube-eng.blogspot.co.uk/2014/03/committing-to-youtube-data-api-v3_4.html
i really hope so as this is by far the best you tube application.
( sorry for posting this in issues but idk where else to post & im sure fellow users would be interested in the answer)
regards

**Comment by ids1024** [comment]
See #256

**Comment by cirrusUK** [comment]
thanks
