### ISSUE TITLE
I quit!

### ISSUE THREAD

**Issue by np1** [np1/mps-youtube#259]
Sadly I won't have enough time to give to open source projects for the foreseeable future. I don't even have time to review the pull requests.

Is anyone interested in taking the lead on this project?

I would be glad to add a collaborator here, otherwise it can continue in a fork.

If you're interested let me know here or by email.

Thanks!

**Comment by knutshub** [comment]
It's really sad to hear that. But a big 'Thank you!' for all your work.

Hopefully, somebody wants to become a collaborator.

**Comment by lol768** [comment]
Thanks for all of your work on this and your other projects, @np1. mps-youtube is a really nice utility, great for background music.

@ids1024 definitely knows his stuff; not sure if he's interested in maintaining the project but I think he'd do a great job.

**Comment by realhu1989** [comment]
What a pity! I think this is one of the most *cool* project I ever meet. I find it just 2 days ago. And install it on my ubuntu. It doesn't work because youtube change the API. But it still looks awesome to me. 
Thank you for all your great work, I hope I can learn python good enough one day to contribute on this project.

**Comment by lol768** [comment]
@realhu1989 You can give https://github.com/np1/mps-youtube/pull/256 a shot if you want to try some experimental support for the latest API.

**Comment by bendem** [comment]
Thanks for everything you did on that amazing project!

**Comment by realhu1989** [comment]
@lol768 thanks , I will try it.

**Comment by hamoid** [comment]
Knowing when to quit is important. Thank you for creating mpsyt! I really enjoyed it during the last months. I hope someone continues development!

**Comment by ids1024** [comment]
That's unfortunate, but I'd be happy to take over, so you can make me a collaborator.

**Comment by zgrimshell** [comment]
@np1 hey man, I am sad to read that you will not have time but I am really thankful for all your work and hope you get back in mpsyt saddle as soon as you can. Based on my observations I do strongly recommend @ids1024 as collaborator as although a fork is an option but in this case it shouldn't be the path as you aren't doing bad coding nor are you hostile upstream. On contrary, one of my best collaborations were with you and I am happy about that. So setting Ian as collaborator would resolve all the current problems and @ids1024 - when you become collaborator please make PR's and release ASAP new version of pafy and mpsyt that resolves whole YT API issues so I can prepare new debian packages and we don't end up in position where mpsyt is useless and should be removed from Debian.

Thanks again @np1 for all your current and future work :)

**Comment by JKatzwinkel** [comment]
@np1 This is sad and comes unexpected. I hope you will only take a hiatus from open source developing, as it would be a pity to lose you for good. I very much admire what you created with mpsyt and will try to make my contribution to its continuance and maintenance. Thank you for everything!
I too would like to suggest @ids1024 as a collaborator at this point as he filed the pull request [https://github.com/np1/mps-youtube/pull/256] and knows the revisions that will port the search functionality to the new API version and make it work again, for which in the opinion of the many people using mpsyt it's probably about time.
Wish you alle the best!

**Comment by xHN35RQ** [comment]
awww, I love mpsyt, and wish you didn't have to quit! But best of luck to you in your endeavours. I recommend @ids1024 as well, as I've been watching his work on the new API and am impressed with his work.

**Comment by Atlantic777** [comment]
Thanks @np1 for your such great work! Don't worry, the community will take care of mps-youtube. :)

**Comment by lloydde** [comment]
Thanks @np1 :100:

**Comment by np1** [comment]
Thanks for all the kind words :) I'm glad people found it useful. 
Thanks to everyone who helped and participated.
Thanks a lot for taking over @ids1024, good to know it's in safe hands. I've added you here and on pafy. I'll look at how to arrange access to update the pypi packages too.

**Comment by ids1024** [comment]
@np1 Just go to the package on pypi and click "roles" in the top bar.

**Comment by ids1024** [comment]
@zgrimshell I have released a new version of mps-youtube, which should work now.

**Comment by xHN35RQ** [comment]
> I have released a new version of mps-youtube, which should work now.

Wow, that was fast! :+1:

**Comment by zgrimshell** [comment]
@ids1024 do you want me to hand you binaries (also for pafy) so you can attach them with .zip and .tar.gz (I sent them previously to @np1 but he probably forgot to attach them) so we can actually remove the Debian branch (to not branch it too much) or do you want binaries and updated debian github branch too? Q: should mpsyt have a hard version dependency on pafy (so like 0.2.4 should go for example with pafy 0.3.66 and above or straight 0.3.72 as some lower version could cause potential lack of features or problems?). Thanks for your work!

**Comment by ids1024** [comment]
@zgrimshell What do you mean by binaries? Debian packages?

> Q: should mpsyt have a hard version dependency on pafy (so like 0.2.4 should go for example with pafy 0.3.66 and above or straight 0.3.72 as some lower version could cause potential lack of features or problems?). Thanks for your work!

Setup.py currently defines the dependency as on pafy>=0.3.72. The package should probably depend on the version of pafy specified in setup.py.

**Comment by zgrimshell** [comment]
@ids1024 yes Debian packages. I will set version dependency in next revision.

**Comment by ids1024** [comment]
Perhaps it would be good to just merge the `debian` branch into develop/master.

**Comment by neo-joko** [comment]
hello (bonjour) from france,
mps was for me a fantastic soft, thank you np1 for your job,
hope the project will go on...
(sorry if my english is bad)

**Comment by neo-joko** [comment]
i've just updated mpsyt, and it's works !!!! great !!! thanks to the communauty

**Comment by zgrimshell** [comment]
@ids1024 yep, just one small problem there - gitignore is having changelog inside so it blocks my debian/changelog file. Not a problem for building a Debian package (lintian will complain and someone can add his own) but it will differ from official ones that I maintain in Debian (tried -f to add but it didn't help). All suits me fine - I can send pull request for you to merge and I also can (as Atom for example does) give you Debian packages and you can add them to release (they are compatible with downstream).

**Comment by GrouchyGaijin** [comment]
@np1  Not to clutter up the thread too much, I'm just a user not a programmer - wanted to say thanks man.  This is without a doubt the coolest YouTube client I have used.  I wish you all the best in the future.

**Comment by ids1024** [comment]
@zgrimshell It's probably fine to just remove that from .gitignore.

**Comment by hrnr** [comment]
@np1 Thanks a lot for your work, I'm sure mps-youtube will go well with @ids1024.

**Comment by ainola** [comment]
Thanks for all your great work, @np1. All I could do is report some bugs and create some clumsy pull requests in the project's infancy but it's really awesome how well it's grown.

**Comment by GijsTimmers** [comment]
@np1 Whenever I posted an issue here, you answered very quickly. And often, a fix would be out in hours. Thank you for the work you put into what became my favourite jukebox.
