### ISSUE TITLE
mps-youtube 0.2.4 doesn't work with mpv

### ISSUE THREAD

**Issue by ShyWest** [np1/mps-youtube#264]
I'm running Debian 8, mpv 0.6.2 and python 2.7.9. After updating to mps-youtube v0.2.4 by running `pip install mps-youtube --upgrade`, mpv stopped working for audio and/or video playback. Trying to play any video yields the following error:
```
The --msglevel option was renamed or replaced: --msg-level (changed semantics)                                         
Error parsing option msglevel (option not found)
Setting commandline option --msglevel=all=no:statusline=status failed.
```
After checking the mpv manpage for both my installed version and the current one, it always should be used the `--msg-level` option.

MPlayer/Mplayer2 still works as intended, so it isn't a big deal. Though sometimes MPlayer doesn't want to play streams, so it's nice to have an option.

**Comment by ids1024** [comment]
I just merged a pull request that should fix this in to the dev version. Try `pip install --upgrade https://github.com/np1/mps-youtube/archive/develop.zip` and see if it works.

**Comment by xHN35RQ** [comment]
You might try running mpv unstable for the latest builds from github. I've been using them successfully for months now without any problems. And mps-youtube works fine with the latest git builds.

**Comment by hrnr** [comment]
I can confirm it works now with dev version on debian 8 with mpv 0.6.2. You can close this one.
