### ISSUE TITLE
"Found nothing for" every search

### ISSUE THREAD

**Issue by lloydde** [np1/mps-youtube#265]
No results found for any searches.

/pink
"Found nothing for pink"

How do I provide information that can help identify the issue? How do I track down if Google Youtube is doing any shenanigans?

~~~
$ mpsyt --version

mpsyt version  : 0.2.4
   notes       : released 13 May 2015
pafy version   : 0.3.72
Python version : 2.7.9 (default, Dec 13 2014, 22:20:22)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
Processor      : i386
Machine type   : x86_64
Architecture   : 64bit,
Platform       : Darwin-14.3.0-x86_64-i386-64bit
sys.stdout.enc : UTF-8
default enc    : ascii
Config dir     : /Users/ll/.config/mps-youtube
env:TERM       : xterm-256color
env:SHELL      : /bin/bash
~~~

~~~
IP related info
Proxy: No Proxy Detected
City: Los Angeles
State/Region: California
Country: US - us flag
ISP: Abovenet Communications Inc
~~~

**Comment by ids1024** [comment]
Run `pip install --upgrade https://github.com/ids1024/mps-youtube/archive/265debug.zip` and try again. You should get a better error message.

**Comment by Varkal** [comment]
I have the same problem. I launch the command. 
Now i got this error : 

    <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>

**Comment by hummelm10** [comment]
Same issue, same error as the others above, but I had noticed it was happening with 0.2.3 as well which is why I tried to upgrade to 0.2.4.

**Comment by lloydde** [comment]
Error message with debug as above, `Problem playing last item: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>`.

Also, reinstalled 0.2.3 to test for same symptom as described by @hummelm10.

**Comment by ids1024** [comment]
Looks like the same issue as rg3/youtube-dl#5317. According to the comments, this command should fix it:

    brew update && brew reinstall openssl

**Comment by lloydde** [comment]
@ids1024 awesome! That resolved the issue.
