### ISSUE TITLE
IRC channel

### ISSUE THREAD

**Issue by zgrimshell** [np1/mps-youtube#270]
Hi @ids1024 , do you think that we should maybe open an IRC channel and promote it as it would be maybe quicker for someone (everyone) to tackle with smaller problems and that people working on mpsyt can collaborate in more sane way (fallbacking to github issues when there is an interesting issue or feature request)? I for example tested the created mpsyt (debian unstable + experimental) and while song searching works, I can't seem to track playlist (trying with .. (double dot)) and it maybe can be change in the code or something which is already mentioned or resolved so I could avoid flooding with duplicate/resolved issue on github.

**Comment by ids1024** [comment]
I've though of the same thing. I just registered `#mps-youtube` on freenode.

**Comment by lol768** [comment]
It'd be great to have the GitHub commit/issue/PR notifications enabled for the channel, @ids1024. I don't know if you could look into this/whether you have access to turn this on. Might be something @np1 needs to look at?

Probably best to run it behind a bouncer to remove the join/part spam (or remove channel mode +n, less desirable).

**Comment by ids1024** [comment]
@lol768 Good idea, but I can't do that myself.

@np1 You can set that up by going to the Webhooks & Services in repo's settings. Add the IRC service. You should probably do that for both mps-youtube and pafy.

**Comment by np1** [comment]
I have added the IRC webhook, I had to register a freenode nick (mps-youtube) to do the notifications.

**Comment by lol768** [comment]
Seems like it works :grinning: 
Thanks @np1

**Comment by ids1024** [comment]
@np1 Could you set the hook to `message without join`? Also, it doesn't seem to be notifying of commits, only pull requests. I think it probably only notifies of pushes to `master`, so the `branches` option should be changed.

Perhaps it would be good to set up a github organization for mps-youtube and pafy? Then I could make these changes myself, and it seems like it would make sense. I guess the organization could be called `mps-youtube`.

Oh, and I just gave you full founder access to the #mps-youtube channel.
