### ISSUE TITLE
new release not work in windows 8

### ISSUE THREAD

**Issue by call5** [np1/mps-youtube#274]
i use mpsyt in windows 8, i'm trying to update for new release based on new API, but i have some issue, here screenshot for more details https://paste.debian.net/plain/177678

**Comment by lol768** [comment]
All images:

![](https://framapic.org/I1OCWvPcjnpD/YkRk8XNq)
![](https://framapic.org/yMYD0wsJ7vup/PnMcoD27)
![](https://framapic.org/Sze61bhEwKyc/ypzKNeeR)
![](https://framapic.org/WK8AgH7PFyWz/ZCwk3OxA)
![](https://framapic.org/n9yZFBY4sBq4/2hOEgfYl)
![](https://framapic.org/a4fx9Gh2Z1b4/TRU8Fakz)
![](https://framapic.org/p1CinknYkAjJ/0J8H9KOT)

**Comment by ids1024** [comment]
Try running `set player mpv.com`.

**Comment by call5** [comment]
if i try to run this i have this issue #223 but this fix https://github.com/np1/mps-youtube/issues/223#issuecomment-76535981 not work i have this http://i.imgur.com/VNX3OEn.png all time i try to update branch develop :/

**Comment by ids1024** [comment]
What version of python do you have? For the current develop branch, it needs to be python 3.

**Comment by call5** [comment]
i have python 3.4 
C:\terminal$ python --version
Python 3.4.2 :: Continuum Analytics, Inc.

**Comment by ids1024** [comment]
May be related to this bug: https://bugs.python.org/issue23121

Where is python installed? You should be able to find out with `where python`.

**Comment by call5** [comment]
the command return this http://i.imgur.com/aXmybM2.png

**Comment by call5** [comment]
content file python.cmd http://i.imgur.com/t8Hdl0q.png

**Comment by ids1024** [comment]
Does the blurred out path contain a space?

**Comment by call5** [comment]
yes

**Comment by ids1024** [comment]
According to the issue I linked to, there are problems with python being installed to a path with a space in it. Could you try re-installing python to a path without one? For example, python on my Windows 7 machine is installed to `C:\Python34`.

**Comment by call5** [comment]
ok , i try to reinstall python

**Comment by call5** [comment]
i reinstall python, but now i have this http://i.imgur.com/srCUohQ.png if i try to run mpsyt after upgrading mps-youtube

**Comment by ids1024** [comment]
Update pafy to the develop branch: `pip install -U https://github.com/np1/pafy/zipball/develop`

**Comment by call5** [comment]
okay thank you it works but now the progress bar repeats itself every second http://i.imgur.com/SFqiFCn.png . but hey I can disable it. thank you for the work and have continued the project

**Comment by ids1024** [comment]
I don't know why it's doing that. You can disable the progress bar with `set show_status false`.

**Comment by call5** [comment]
ok thanks you very much, good job and good soft

**Comment by ids1024** [comment]
I pushed a commit that should fix that issue. Reinstall the develop branch and `show_status` should work correctly.

**Comment by call5** [comment]
ok i close my computer, i do that tomorroy, thanks you

**Comment by call5** [comment]
your commit fix issue about progress bar,  good job, thanks, i close this issue now
