### ISSUE TITLE
Is there a way to set window monitor?

### ISSUE THREAD

**Issue by gsmafra** [np1/mps-youtube#278]
Set window_pos and set window_size work well, but since I am using double monitors the application seems to not know in which monitor to place the screen, and therefore it places it always in the left one. If I want it to be placed in the right monitor, how could I do it? I am using Ubuntu 14.04, in Unity there is no such thing as primary and secondary monitor.

**Comment by ids1024** [comment]
You can use `set playerargs` to pass arbitrary arguments to mpv/mplayer. Mpv's `--screen` option should work.

**Comment by gsmafra** [comment]
Done, simple as that. <set playerargs --screen=0>
