### ISSUE TITLE
Updating on Mac

### ISSUE THREAD

**Issue by mhmtk** [np1/mps-youtube#285]
Hi,
I already have mps-youtube installed, and I need to update it. I'm running
pip install mps-youtube --upgrade
but I get the error"
Downloading/unpacking mps-youtube from https://pypi.python.org/packages/py2.py3/m/mps-youtube/mps_youtube-0.2.4-py2.py3-none-any.whl#md5=62f17427a61faea6304379b16fdee061
  Downloading mps_youtube-0.2.4-py2.py3-none-any.whl (57kB): 57kB downloaded
Downloading/unpacking pafy>=0.3.72 (from mps-youtube)
  Downloading Pafy-0.3.72-py2.py3-none-any.whl
Installing collected packages: mps-youtube, pafy
  Found existing installation: mps-youtube 0.01.46
    Uninstalling mps-youtube:
Cleaning up...
Isn't there a version after 0.01.46? Why is it not trying to install the latest version?
Thank you!

**Comment by mhmtk** [comment]
Also, when I tried uninstalling I got this:
pip uninstall mps-youtube
Uninstalling mps-youtube:
  /Library/Python/2.7/site-packages/mps_youtube-0.01.46.dist-info/DESCRIPTION.rst
  /Library/Python/2.7/site-packages/mps_youtube-0.01.46.dist-info/METADATA
  /Library/Python/2.7/site-packages/mps_youtube-0.01.46.dist-info/RECORD
  /Library/Python/2.7/site-packages/mps_youtube-0.01.46.dist-info/WHEEL
  /Library/Python/2.7/site-packages/mps_youtube-0.01.46.dist-info/entry_points.txt
  /Library/Python/2.7/site-packages/mps_youtube-0.01.46.dist-info/metadata.json
  /Library/Python/2.7/site-packages/mps_youtube-0.01.46.dist-info/top_level.txt
  /Library/Python/2.7/site-packages/mps_youtube/__init__.py
  /Library/Python/2.7/site-packages/mps_youtube/__init__.pyc
  /Library/Python/2.7/site-packages/mps_youtube/main.py
  /Library/Python/2.7/site-packages/mps_youtube/main.pyc
  /usr/local/bin/mpsyt
Proceed (y/n)? y
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/commands/uninstall.py", line 59, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 1035, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 598, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 1836, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/util.py", line 295, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/mps_youtube-0.01.46.dist-info/DESCRIPTION.rst'

**Comment by meesameesa** [comment]
Hi mhmtk,

Errno 13 typically refers to the user not having permissions on the file(s)/directory(ies) in question. Have you tried with escalated user?

**Comment by mhmtk** [comment]
Oh yea, i was missing the sudo. It worked! Uninstalling then reinstalling was also a get around for my update problem, thx!
