### ISSUE TITLE
Some videos are not playing

### ISSUE THREAD

**Issue by fa7ad** [np1/mps-youtube#292]
~~Whenever I choose a VEVO video,~~ On some videos, it shows the file size etc and then goes back to the search results page

**Comment by lol768** [comment]
> user taylorswiftvevo
> 1

Appears to work for me (plays "blank space" without any issues). 

Which particular videos don't work for you?

**Comment by PuKoren** [comment]
(This should be a feature!)
Seriously, can you provide some exemple? I tried and it works fine on my comp

**Comment by fa7ad** [comment]
Its not just vevo, some vevo videos play others don't.
try this
> .akcent my passion
> 1

or
> url ay_fw54W2Fg
> 1

**Comment by PuKoren** [comment]
Works well for me with this URL.
Do you use the latest version? Wich OS/Player?
I'm on Arch Linux with mplayer

**Comment by fa7ad** [comment]
I'm on Ubuntu, using mplayer.
And yes I have the latest version

**Comment by fa7ad** [comment]
Ok, I just installed *mpv* and it pulled a few libavfilter packages, now its working fine.
so, /closed i guess
