### ISSUE TITLE
Search for youtube playlist not working since 0.2.4 

### ISSUE THREAD

**Issue by tioduke** [np1/mps-youtube#295]
Searching for playlist with // is broken (no results) since 0.2.4. If I revert back to 0.2.3, it works (I get results).

For example: //Postmodern jukebox gives a list of playlist in 0.2.3. But it gives "No playlists found for: Postmodern jukebox" in 0.2.4

**Comment by ids1024** [comment]
Duplicate of #282. Fixed in git, will work in next release.

**Comment by tioduke** [comment]
Thank you. Sorry for the duplicate.
