### ISSUE TITLE
Does the development version only works with Python3?

### ISSUE THREAD

**Issue by laapsaap** [np1/mps-youtube#298]
```
$ mpsyt 
Traceback (most recent call last):
  File "/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.4', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/mps_youtube/__init__.py", line 1, in <module>
    from .main import init
  File "/usr/lib/python2.7/site-packages/mps_youtube/main.py", line 54, in <module>
    from urllib.request import urlopen, build_opener
ImportError: No module named request
```

Python3 ?- >ImportError: No module named request

**Comment by Atlantic777** [comment]
Here's what I have found out for now.

I can run development version only with python 3 but I can't play any videos.
I can't run development version with python 2.

Dev version has support for playlist search and latest stable release does not.

What is actually happening?

**Comment by hrnr** [comment]
Hi, dev version is indeed python3-only. Also playlist search was fixed in dev version (due to move to new youtube api).

I'm not sure why you can't play any videos, I use happily dev version with mpv.

**Comment by Atlantic777** [comment]
Hm, I thought that it's just a temporary problem and dev version is broken. Thanks for the info, I'll open a new issue and try to solve it.

**Comment by ids1024** [comment]
Playlist search is broken due to issue #282. As a workaround you can use `set search_music false` or run the dev version.

Support for python 2 was intentionally dropped, and python 3 is now required.
