### ISSUE TITLE
ImportError: No module named request on Windows

### ISSUE THREAD

**Issue by GijsTimmers** [np1/mps-youtube#305]
When starting `mpsyt.exe` from `cmd`, mps-youtube does not start:

```
Microsoft Windows [versie 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle rechten voorbehouden.

C:\Users\User>mpsyt.exe
Traceback (most recent call last):
  File "C:\Python27\Scripts\mpsyt-script.py", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "C:\python27\lib\site-packages\pkg_resources.py", line 356, in load_entry
_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\python27\lib\site-packages\pkg_resources.py", line 2472, in load_entr
y_point
    return ep.load()
  File "C:\python27\lib\site-packages\pkg_resources.py", line 2186, in load
    ['__name__'])
  File "C:\python27\lib\site-packages\mps_youtube\__init__.py", line 1, in <modu
le>
    from .main import init
  File "C:\python27\lib\site-packages\mps_youtube\main.py", line 54, in <module>

    from urllib.request import urlopen, build_opener
ImportError: No module named request

C:\Users\User>
```

I'm running mps-youtube 0.2.5:

```
C:\Users\User>pip.exe list
colorama (0.3.1)
colorconsole (0.7.1)
cx-Freeze (4.3.3)
distribute (0.7.3)
keyring (4.0)
mechanize (0.2.5)
mps-youtube (0.2.5)
netifaces (0.10.4)
numpy (1.9.1)
pafy (0.3.74)
pip (1.5.6)
progressbar-latest (2.4)
PyInstaller (2.1)
pywin32 (219)
requests (2.7.0)
setuptools (5.7)
tabulate (0.7.3)
urllib3 (1.10.4)
youtube-dl (2015.05.20)
```

**Comment by lol768** [comment]
>Python27

Please consider using `pip3` or similar. I don't think Python 2 is supported.

**Comment by GijsTimmers** [comment]
@lol768 That fixed it! Thank you.

For those after me:

    sudo pip uninstall mps-youtube
    sudo apt-get install python3-pip
    sudo pip3 install mps-youtube

**Comment by myleandro** [comment]
@GijsTimmers question - how on earth didja get apt-get and sudo onto windows? :)

**Comment by myleandro** [comment]
For others (part 2): 
1. Cygwin && install python3 and wget (./setup-x86_64.exe). You can have python2.7 installed side by side (I did - check which is default with python -v, but also run python3 to verify it is installed and in path)
2. Grab get-pip.py ( wget https://bootstrap.pypa.io/get-pip.py)
3. pip3 list (ensure using python3 version of request is there as per above thread) 
4. pip3 install colorama && pip3 install mps-youtube
5. mpsyt - you're good to go.

**Comment by GijsTimmers** [comment]
Heh. Turned out I had the problem on both Windows and Ubuntu, which makes sense. Edited.
