### ISSUE TITLE
Error Trying to start mpsyt on mac

### ISSUE THREAD

**Issue by gotama** [np1/mps-youtube#309]
I have searched google for this issue, but can't seem to figure it out.  This is my last attempt at finding help.

Regards,

James

jamess-mbp:~ james$ mpsyt 
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 7, in <module>
    from mps_youtube import main
  File "/Library/Python/2.7/site-packages/mps_youtube/__init__.py", line 1, in <module>
    from .main import init
  File "/Library/Python/2.7/site-packages/mps_youtube/main.py", line 54, in <module>
    from urllib.request import urlopen, build_opener
ImportError: No module named request

**Comment by gotama** [comment]
I also tried installing request from pip
 pip install request
Collecting request
  Could not find a version that satisfies the requirement request (from versions: )
No matching distribution found for request

**Comment by hrnr** [comment]
Hi, python 2 support was dropped in latest version of mps-youtube. Try installing mps-youtube with pip3.

**Comment by ids1024** [comment]
As @hrnr said, python 2 in now unsuported. Since this is confusing people, I have added a message to setup.py in the development version to say this when run with python 2: 0f83e42951a49871a550e4305429081cca35174d.

**Comment by gotama** [comment]
Ok cool got it all sorted... Python 3 solved it all.

Thanks for the effort guys

Regards,

James
